stages:
  - build
  - deploy

variables:
  PROJECT_ID: unlimitedmarketplace
  REGION: your-gcp-region
  GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY

services:
  - docker:dind

build:
  stage: build
  script:
    - cd sem3-fe
    - bash build_and_push.sh

deploy:
  stage: deploy
  script:
    - echo "Deployment completed"
  only:
    - workbranch

