stages:
  - build_and_test
  - docker_build
  - deploy

variables:
  PROJECT_ID: unlimitedmarketplace
  REGION: europe-north1
  GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY

services:
  - docker:dind

build_and_test:
  stage: build_and_test
  image: node:14-alpine
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build
  tags:
    - docker
  only:
    - workbranch

docker_build:
  stage: docker_build
  image: google/cloud-sdk:latest
  before_script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project $PROJECT_ID
    - gcloud services enable artifactregistry.googleapis.com
    - gcloud auth configure-docker
  script:
    - docker build -t gcr.io/$PROJECT_ID/unlimitedmarketplace-frontend:latest -f Dockerfile .
    - docker push gcr.io/$PROJECT_ID/unlimitedmarketplace-frontend:latest
  tags:
    - docker
  only:
    - workbranch


deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  before_script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project $PROJECT_ID
    - gcloud services enable run.googleapis.com
  script:
    - >
      BACKEND_URL=$(cat backend_url.env | grep REACT_APP_BACKEND_URL | cut -d '=' -f 2) && \
      echo "Using Backend URL: $BACKEND_URL" && \
      gcloud run deploy unlimitedmarketplace-frontend --image gcr.io/$PROJECT_ID/unlimitedmarketplace-frontend:latest --region $REGION --platform managed --allow-unauthenticated --update-env-vars "REACT_APP_BACKEND_URL=$BACKEND_URL"
  dependencies:
    - deploy  # This makes sure the backend_url.env file from the backend deploy stage is available
  environment:
    name: production
    url: https://unlimitedmarketplace-frontend.$REGION.run.app
  tags:
    - docker
  only:
    - workbranch

