stages:
  - build
  - deploy

variables:
  PROJECT_ID: unlimitedmarketplace
  REGION: europe-north1
  GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY

services:
  - docker:dind

before_script:
  # Install Google Cloud SDK
  - pwsh -Command 'Invoke-WebRequest https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.zip -OutFile google-cloud-sdk.zip; Expand-Archive google-cloud-sdk.zip -DestinationPath $Env:USERPROFILE; Remove-Item google-cloud-sdk.zip; $Env:USERPROFILE\google-cloud-sdk\install.bat'
  - pwsh -Command '$env:PATH += ";$Env:USERPROFILE\google-cloud-sdk\bin"; gcloud --quiet components update; gcloud --quiet components install kubectl'

  # Authenticate with Google Cloud
  - pwsh -Command 'echo $Env:GCLOUD_SERVICE_KEY | Out-File -FilePath $Env:HOME\gcloud-service-key.b64 -Encoding ascii'
  - pwsh -Command '[System.Convert]::FromBase64String((Get-Content -Raw -Path $Env:HOME\gcloud-service-key.b64)) | ForEach-Object { $_ } | Set-Content -Path $Env:HOME\gcloud-service-key.json -AsByteStream'
  - pwsh -Command 'gcloud auth activate-service-account --key-file $Env:HOME\gcloud-service-key.json'
  - pwsh -Command 'gcloud config set project $Env:PROJECT_ID'
  - pwsh -Command 'gcloud auth configure-docker'
  - pwsh -Command 'gcloud services enable artifactregistry.googleapis.com'
  - pwsh -Command 'gcloud services enable run.googleapis.com'


build:
  stage: build
  script:
    - bash build_and_push.sh
  tags:
    - docker
  only:
    - workbranch

