stages:
  - build
  - docker_build
  - deploy

variables:
  PROJECT_ID: unlimitedmarketplace
  REGION: europe-north1
  GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

build:
  stage: build
  image: node:14
  script:
    - npm install
    - CI=false npm run build  # Disable treating warnings as errors
  artifacts:
    paths:
      - build/
  tags:
    - docker
  only:
    - workbranch

docker_build:
  stage: docker_build
  image: google/cloud-sdk:latest
  before_script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project $PROJECT_ID
    - gcloud auth configure-docker
  script:
    - docker build -t gcr.io/$PROJECT_ID/sem3-fe:latest -f Dockerfile .
    - docker push gcr.io/$PROJECT_ID/sem3-fe:latest
  tags:
    - docker
  only:
    - workbranch

deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  before_script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project $PROJECT_ID
    - gcloud auth configure-docker
    - gcloud services enable run.googleapis.com
  script:
    - BACKEND_URL=$(gcloud run services describe unlimitedmarketplace-backend --platform managed --region $REGION --format="value(status.url)")
    - gcloud run deploy sem3-fe-frontend --image gcr.io/$PROJECT_ID/sem3-fe:latest --region $REGION --platform managed --allow-unauthenticated --update-env-vars "REACT_APP_BACKEND_URL=$BACKEND_URL"
  tags:
    - docker
  only:
    - workbranch





