stages:
  - build_and_test
  - docker_build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"
  PROJECT_ID: unlimitedmarketplace
  REGION: europe-north1
  GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY

services:
  - docker:dind

build_and_test:
  stage: build_and_test
  image: node:latest
  script:
    - npm install
    - npm run build
  tags:
    - docker

docker_build:
  stage: docker_build
  image: google/cloud-sdk:latest
  before_script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project $PROJECT_ID
    - gcloud services enable artifactregistry.googleapis.com
    - gcloud auth configure-docker
  script:
    - docker build -t gcr.io/$PROJECT_ID/unlimitedmarketplace-fe:latest -f Dockerfile .
    - docker push gcr.io/$PROJECT_ID/unlimitedmarketplace-fe:latest
  tags:
    - docker
  only:
    - workbranch
    
deploy_frontend:
  stage: deploy
  image: google/cloud-sdk:latest
  before_script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project $PROJECT_ID
    - gcloud services enable run.googleapis.com
    - curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "https://gitlab.com/api/v4/projects/<backend-project-id>/jobs/artifacts/main/raw/backend_url.env?job=deploy" --output backend_url.env
    - source backend_url.env
  script:
    - gcloud run deploy unlimitedmarketplace-frontend --image gcr.io/$PROJECT_ID/unlimitedmarketplace-fe:latest --region $REGION --platform managed --allow-unauthenticated --update-env-vars "REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL"
  environment:
    name: production
    url: https://unlimitedmarketplace-frontend.$REGION.run.app
  tags:
    - docker
  only:
    - workbranch